version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: multi_one
    ports:
      - "5432:5432"
    volumes:
      - multi-one:/var/lib/postgres

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'multi_two'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - '3306:3306'
    volumes:
      - multi-two:/var/lib/mysql

volumes:
  multi-one:
  multi-two: