CREATE TABLE DATA_SOURCE_CONFIGS
(
    TENANT              VARCHAR(100) PRIMARY KEY,
    DRIVER_CLASS_NAME VARCHAR(255),
    URL               VARCHAR(255),
    USERNAME          VARCHAR(20),
    PASSWORD         VARCHAR(50)
)